# Generated by Django 6.0.2 on 2026-02-05 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadePC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='FuncaoPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='SerieDocumentalPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=11, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('tipo_prazo_corrente', models.CharField(choices=[('C', 'Até a aprovação das contas'), ('P', 'Período determinado'), ('V', 'Vigência')], default='V', max_length=1, verbose_name='Tipo de Prazo Corrente')),
                ('prazo_corrente', models.PositiveIntegerField(verbose_name='Prazo na Fase Corrente (anos)')),
                ('prazo_central', models.PositiveIntegerField(verbose_name='Prazo no Arquivo Central (anos)')),
                ('destinacao', models.CharField(choices=[('E', 'Eliminar'), ('P', 'Preservar')], default='P', max_length=1, verbose_name='Destinação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('legislacao_norma', models.TextField(blank=True, verbose_name='Legislação/Norma')),
                ('atividade_mae', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arq_app.atividadepc', verbose_name='Atividade Mãe')),
            ],
        ),
        migrations.CreateModel(
            name='SubFuncaoPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('funcao_mae', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arq_app.funcaopc', verbose_name='Função Mãe')),
            ],
        ),
        migrations.AddField(
            model_name='atividadepc',
            name='subfuncao_mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arq_app.subfuncaopc', verbose_name='Subfunção Mãe'),
        ),
    ]
