# Generated by Django 6.0.2 on 2026-02-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arq_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interessado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('tipo_doc', models.CharField(choices=[('F', 'CPF'), ('J', 'CNPJ'), ('N', 'Não Possui')], default='N', max_length=1, verbose_name='Tipo de Documento')),
                ('numero_doc', models.CharField(blank=True, max_length=20, verbose_name='Número do Documento')),
            ],
            options={
                'verbose_name': 'Interessado',
                'verbose_name_plural': 'Interessados',
            },
        ),
        migrations.AlterModelOptions(
            name='atividadepc',
            options={'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades'},
        ),
        migrations.AlterModelOptions(
            name='funcaopc',
            options={'verbose_name': 'Função', 'verbose_name_plural': 'Funções'},
        ),
        migrations.AlterModelOptions(
            name='seriedocumentalpc',
            options={'verbose_name': 'Série Documental', 'verbose_name_plural': 'Séries Documentais'},
        ),
        migrations.AlterModelOptions(
            name='subfuncaopc',
            options={'verbose_name': 'Subfunção', 'verbose_name_plural': 'Subfunções'},
        ),
    ]
