# Generated by Django 6.0.2 on 2026-02-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arq_app', '0002_interessado_alter_atividadepc_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaixaDeArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número da Caixa')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('cod_localizacao', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de Localização')),
            ],
            options={
                'verbose_name': 'Caixa de Arquivo',
                'verbose_name_plural': 'Caixas de Arquivo',
            },
        ),
    ]
