# Generated by Django 6.0.2 on 2026-02-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arq_app', '0003_caixadearquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixadearquivo',
            name='numero',
            field=models.PositiveIntegerField(unique=True, verbose_name='Número da Caixa'),
        ),
    ]
