# Generated by Django 6.0.2 on 2026-02-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arq_app', '0004_alter_caixadearquivo_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numerador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_num', models.PositiveBigIntegerField(default=0, verbose_name='último número')),
            ],
        ),
    ]
