# Generated by Django 6.0.2 on 2026-02-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arq_app', '0005_numerador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interessado',
            name='numero_doc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do Documento'),
        ),
    ]
