# Generated by Django 6.0.2 on 2026-02-20 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arq_app', '0006_alter_interessado_numero_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_controle', models.CharField(blank=True, max_length=30, verbose_name='Código de Controle')),
                ('codigo_protocolo', models.CharField(blank=True, max_length=30, verbose_name='Código de Protocolo')),
                ('data_producao', models.DateField(verbose_name='Data de Produção')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('data_encerramento', models.DateField(blank=True, null=True, verbose_name='Data de Encerramento')),
                ('quantidade_volumes', models.PositiveIntegerField(default=1, verbose_name='Quantidade de Volumes')),
                ('caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='arq_app.caixadearquivo', verbose_name='Caixa de Arquivo')),
                ('interessado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arq_app.interessado', verbose_name='Interessado')),
                ('serie_documental', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arq_app.seriedocumentalpc', verbose_name='Série Documental')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
