# Generated by Django 6.0.2 on 2026-03-26 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arq_app', '0007_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoEliminacaoDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroTermo', models.CharField(max_length=20, unique=True, verbose_name='Número do Termo')),
                ('dataTermo', models.DateField(verbose_name='Data do Termo')),
                ('numeroEdital', models.CharField(max_length=20, unique=True, verbose_name='Número do Edital')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Termo de Eliminação de Documentos',
                'verbose_name_plural': 'Termos de Eliminação de Documentos',
            },
        ),
        migrations.AlterField(
            model_name='atividadepc',
            name='subfuncao_mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividades', to='arq_app.subfuncaopc', verbose_name='Subfunção Mãe'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='caixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='arq_app.caixadearquivo', verbose_name='Caixa de Arquivo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='interessado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='arq_app.interessado', verbose_name='Interessado'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='serie_documental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='arq_app.seriedocumentalpc', verbose_name='Série Documental'),
        ),
        migrations.AlterField(
            model_name='seriedocumentalpc',
            name='atividade_mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series_documentais', to='arq_app.atividadepc', verbose_name='Atividade Mãe'),
        ),
        migrations.AlterField(
            model_name='subfuncaopc',
            name='funcao_mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subfuncoes', to='arq_app.funcaopc', verbose_name='Função Mãe'),
        ),
        migrations.AddField(
            model_name='caixadearquivo',
            name='termoEliminacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixas_eliminadas', to='arq_app.termoeliminacaodocumentos', verbose_name='Termo de Eliminação'),
        ),
    ]
